package org.drools.generated;

declare TaxPayer
    taxpayerId : String
    income : double
    taxRate : int
end

rule "Assign Tax Rate for Income Less Than 30000"
when
    $tp : TaxPayer(income < 30000)
then
    modify($tp) { setTaxRate(10) }
end

rule "Assign Tax Rate for Income Between 30000 and 79999"
when
    $tp : TaxPayer(income >= 30000, income < 80000)
then
    modify($tp) { setTaxRate(22) }
end

rule "Assign Tax Rate for Income Greater Than or Equal to 80000"
when
    $tp : TaxPayer(income >= 80000)
then
    modify($tp) { setTaxRate(32) }
end