package org.drools.generated;

declare TaxPayer
    taxpayerId : String
    income : double
    taxRate : int
end

rule "Set Tax Rate 10%"
salience 10
when
    $t : TaxPayer(income < 30000, taxRate == 0)
then
    modify($t) { setTaxRate(10) }
end

rule "Set Tax Rate 22%"
salience 50
when
    $t : TaxPayer(income >= 30000, income < 80000, taxRate == 0)
then
    modify($t) { setTaxRate(22) }
end

rule "Set Tax Rate 32%"
salience 100
when
    $t : TaxPayer(income >= 80000, taxRate == 0)
then
    modify($t) { setTaxRate(32) }
end