package org.drools.generated;

declare Password
    value : String
    length : int
    strength : String
end

rule "Password Weak"
when
    $p : Password(length < 8)
then
    modify($p) { setStrength("WEAK") }
end

rule "Password Medium"
when
    $p : Password(length >= 8 && length <= 12)
then
    modify($p) { setStrength("MEDIUM") }
end

rule "Password Strong"
when
    $p : Password(length > 12)
then
    modify($p) { setStrength("STRONG") }
end