package org.drools.generated;

declare Person
    name : String
    age : int
    category : String
end

rule "Classify as CHILD"
    when
        $p : Person(age < 13)
    then
        modify($p) { setCategory("CHILD") }
end

rule "Classify as TEEN"
    when
        $p : Person(age >= 13, age <= 19)
    then
        modify($p) { setCategory("TEEN") }
end

rule "Classify as ADULT"
    when
        $p : Person(age >= 20, age <= 64)
    then
        modify($p) { setCategory("ADULT") }
end

rule "Classify as SENIOR"
    when
        $p : Person(age >= 65)
    then
        modify($p) { setCategory("SENIOR") }
end