package org.drools.generated;

declare Password
    value: String
    length: int
    strength: String
end

rule "Password Strength - Weak"
when
    $p : Password(length < 8)
then
    modify($p) {
        setStrength("WEAK")
    }
end

rule "Password Strength - Medium"
when
    $p : Password(length >= 8, length <= 12)
then
    modify($p) {
        setStrength("MEDIUM")
    }
end

rule "Password Strength - Strong"
when
    $p : Password(length > 12)
then
    modify($p) {
        setStrength("STRONG")
    }
end