package org.drools.generated;

declare TaxPayer
    taxpayerId : String
    income : double
    taxRate : int
end

rule "Assign Tax Rate for Income Less Than 30000"
when
    $taxPayer : TaxPayer(income < 30000)
then
    modify($taxPayer) {
        setTaxRate(10)
    }
end

rule "Assign Tax Rate for Income Between 30000 and 80000"
when
    $taxPayer : TaxPayer(income >= 30000, income < 80000)
then
    modify($taxPayer) {
        setTaxRate(22)
    }
end

rule "Assign Tax Rate for Income Greater Than or Equal to 80000"
when
    $taxPayer : TaxPayer(income >= 80000)
then
    modify($taxPayer) {
        setTaxRate(32)
    }
end