package org.drools.generated;

declare Password
    value : String
    length : int
    strength : String
end

rule "Set Strength Weak"
salience 100
when
    $p : Password(length < 8, strength == null)
then
    modify($p) { setStrength("WEAK") }
end

rule "Set Strength Medium"
salience 50
when
    $p : Password(length >= 8, length <= 12, strength == null)
then
    modify($p) { setStrength("MEDIUM") }
end

rule "Set Strength Strong"
salience 10
when
    $p : Password(length > 12, strength == null)
then
    modify($p) { setStrength("STRONG") }
end