package org.drools.generated;

declare Ticket
    ticketId : String
    severity : String
    priority : int
end

rule "Set Priority - Critical"
salience 100
when
    $t : Ticket(severity == "CRITICAL", priority == 0)
then
    modify($t) { setPriority(1) }
end

rule "Set Priority - High"
salience 90
when
    $t : Ticket(severity == "HIGH", priority == 0)
then
    modify($t) { setPriority(2) }
end

rule "Set Priority - Medium"
salience 80
when
    $t : Ticket(severity == "MEDIUM", priority == 0)
then
    modify($t) { setPriority(3) }
end

rule "Set Priority - Low"
salience 70
when
    $t : Ticket(severity == "LOW", priority == 0)
then
    modify($t) { setPriority(4) }
end