package com.github.rikkola.drlgen.model;

import java.util.List;
import java.util.Map;

/**
 * Defines a rule to be generated by the AI model.
 * This is the core input model for DRL generation - without test-specific fields.
 */
public record RuleDefinition(
        String name,
        String description,
        String requirement,
        List<FactTypeDefinition> factTypes
) {
    /**
     * Definition of a fact type for DRL generation.
     */
    public record FactTypeDefinition(
            String typeName,
            Map<String, String> fields  // fieldName -> fieldType
    ) {
        /**
         * Generates a human-readable description for the AI agent.
         */
        public String toDescription() {
            StringBuilder sb = new StringBuilder(typeName).append(" {\n");
            fields.forEach((field, type) ->
                    sb.append("    ").append(field).append(": ").append(type).append("\n"));
            sb.append("}");
            return sb.toString();
        }
    }

    /**
     * Generates a human-readable fact types description for the AI agent.
     */
    public String getFactTypesDescription() {
        StringBuilder sb = new StringBuilder();
        for (FactTypeDefinition ft : factTypes) {
            sb.append("- ").append(ft.typeName()).append(":\n");
            ft.fields().forEach((field, type) ->
                    sb.append("    ").append(field).append(": ").append(type).append("\n"));
        }
        return sb.toString();
    }
}
