package org.drools.generated;

declare Password
    value : String
    length : int
    strength : String
end

rule "Password Strength Weak"
salience 100
when
    $p : Password(length < 8, strength == null)
then
    modify($p) { setStrength("WEAK") }
end

rule "Password Strength Medium"
salience 90
when
    $p : Password(length >= 8 && length <= 12, strength == null)
then
    modify($p) { setStrength("MEDIUM") }
end

rule "Password Strength Strong"
salience 80
when
    $p : Password(length > 12, strength == null)
then
    modify($p) { setStrength("STRONG") }
end