package org.drools.generated;

declare Ticket
    ticketId : String
    severity : String
    priority : int
end

rule "Set Priority to 1 for CRITICAL severity"
when
    $t : Ticket( severity == "CRITICAL", priority != 1 )
then
    modify( $t ) { setPriority( 1 ) }
end

rule "Set Priority to 2 for HIGH severity"
when
    $t : Ticket( severity == "HIGH", priority != 2 )
then
    modify( $t ) { setPriority( 2 ) }
end

rule "Set Priority to 3 for MEDIUM severity"
when
    $t : Ticket( severity == "MEDIUM", priority != 3 )
then
    modify( $t ) { setPriority( 3 ) }
end

rule "Set Priority to 4 for LOW severity"
when
    $t : Ticket( severity == "LOW", priority != 4 )
then
    modify( $t ) { setPriority( 4 ) }
end