package org.drools.generated;

declare Password
    value : String
    length : int
    strength : String
end

rule "Set Strength STRONG"
salience 100
when
    $p : Password(length > 12, strength == "NONE")
then
    modify($p) { setStrength("STRONG") }
end

rule "Set Strength MEDIUM"
salience 50
when
    $p : Password(length >= 8, length <= 12, strength == "NONE")
then
    modify($p) { setStrength("MEDIUM") }
end

rule "Set Strength WEAK"
salience 10
when
    $p : Password(length < 8, strength == "NONE")
then
    modify($p) { setStrength("WEAK") }
end