package org.drools.generated;

declare Password
    value : String
    length : int
    strength : String
end

rule "Set Password Strength - Strong"
salience 100
when
    $p : Password(length > 12, strength == "NONE")
then
    modify($p) { setStrength("STRONG") }
end

rule "Set Password Strength - Medium"
salience 90
when
    $p : Password(length >= 8 && length <= 12, strength == "NONE")
then
    modify($p) { setStrength("MEDIUM") }
end

rule "Set Password Strength - Weak"
salience 10
when
    $p : Password(length < 8, strength == "NONE")
then
    modify($p) { setStrength("WEAK") }
end