package org.drools.generated;

declare Person
    name : String
    age : int
    category : String
end

rule "Set Child Category"
when
    $p : Person(age < 13, category == "NONE")
then
    modify($p) { setCategory("CHILD") }
end

rule "Set Teen Category"
when
    $p : Person(age >= 13 && age <= 19, category == "NONE")
then
    modify($p) { setCategory("TEEN") }
end

rule "Set Adult Category"
when
    $p : Person(age >= 20 && age <= 64, category == "NONE")
then
    modify($p) { setCategory("ADULT") }
end

rule "Set Senior Category"
when
    $p : Person(age >= 65, category == "NONE")
then
    modify($p) { setCategory("SENIOR") }
end