package org.drools.generated;

declare TaxPayer
    taxpayerId : String
    income : double
    taxRate : int
end

rule "Tax Rate - 10%"
salience 100
when
    $tp : TaxPayer(income < 30000, taxRate == 0)
then
    modify($tp) { setTaxRate(10) }
end

rule "Tax Rate - 22%"
salience 90
when
    $tp : TaxPayer(income >= 30000 && income < 80000, taxRate == 0)
then
    modify($tp) { setTaxRate(22) }
end

rule "Tax Rate - 32%"
salience 10
when
    $tp : TaxPayer(income >= 80000, taxRate == 0)
then
    modify($tp) { setTaxRate(32) }
end